import type { NextPage } from 'next';
import Head from 'next/head';
import Container from '../components/Container';
import Envelope from '../components/Envelope';

const Home: NextPage = () => {
	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col justify-center text-center">
				<Envelope>
					<h2>Content</h2>
				</Envelope>
			</div>
		</Container>
	);
};

export default Home;
